### ISSUE TITLE
Homepage note is frequently cleared blank 

### ISSUE THREAD

**Issue by machado-t** [mirnovov/obsidian-homepage#69] opened 2023-09-08 09:49 UTC
### Details

Very frequently, the homepage note is cleared empty. I don't know what's causing this, but i believe this plugin is causing it.

### Steps to reproduce

My plugin has the following settings:
- "file" homepage
- Open on startup: yes
- Open when empty: yes
- Use when opening normally: yes
- Separate mobile homepage: no
- Commands: none
- Opening method: Keep open notes
- Manual opening mode: Keep open notes
- Auto-create: No
- Pin: No
- Homepage view: Reading view
- Revert view on close: yes
- Auto-scroll: no
- Refresh dataview: no

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment] 2023-09-08 09:54
Can you paste your debug information here? It's a button in the bottom of the Homepage settings.

**Comment by machado-t** [comment] 2023-09-08 17:50
Sorry, I just noticed there was a recent update. I was on 3.5.1.

Here's the debug info anyway, but maybe we should wait and see if the problem persists in 3.5.2:

{"version":3,"homepages":{"Main Homepage":{"value":"Dashboard","kind":"File","openOnStartup":true,"hasRibbonIcon":true,"openMode":"Keep open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":true,"openWhenEmpty":true,"refreshDataview":false,"autoCreate":false,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":true},"Mobile Homepage":{"value":"Dashboard","kind":"File","openOnStartup":true,"hasRibbonIcon":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Default view","revertView":true,"openWhenEmpty":true,"refreshDataview":false,"autoCreate":true,"autoScroll":false,"pin":false,"commands":[],"alwaysApply":true}},"separateMobile":false,"_defaultViewMode":"default","_livePreview":"default","_focusNewTab":"default","_plugins":["ai-commander","obsidian-auto-link-title","buttons","calendar","callout-manager","cmdr","obsidian-custom-frames","dataview","cm-editor-syntax-highlight-obsidian","obsidian-excel-to-markdown-table","google-calendar","obsidian-hide-sidebars-when-narrow","obsidian-hider","obsidian-minimal-settings","obsidian-enhancing-export","obsidian42-brat","obsidian-outliner","periodic-notes","recent-files-obsidian","remember-cursor-position","obsidian-rich-links","obsidian-style-settings","templater-obsidian","obsidian-wordy","obsidian-zotero-desktop-connector","bibnotes","dbfolder","obsidian-text-format","markdown-table-editor","workspaces-plus","copilot","text-extractor","obsidian-completr","table-editor-obsidian","obsidian-dictionary-plugin","mousewheel-image-zoom","obsidian-omnivore","notion-like-tables","link-tree","obsidian-plugin-update-tracker","obsidian-importer","dashboards","mini-toolbar","supercharged-links-obsidian","quickadd","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","properties","page-preview","note-composer","command-palette","editor-status","bookmarks","outline","word-count","audio-recorder","workspaces","file-recovery"],"_obsidianVersion":"1.4.5"}

**Comment by machado-t** [comment] 2023-09-09 09:38
Can confirm the problem persists with 3.5.2.

**Comment by mirnovov** [comment] 2023-09-09 10:52
Can’t reproduce it, even with all your plugins installed. I’m guessing it’s something to do with an interaction between this and another plugin, but I’m not certain. I’ll continue looking into it.

**Comment by mirnovov** [comment] 2023-09-10 05:15
@machado-t what kind of stuff do you have on your Dashboard note? and for syncing, do you use non-Obsidian solution, like iCloud?

**Comment by machado-t** [comment] 2023-09-10 10:41
Buttons to perform quick add actions and dataview lists. I do use OneDrive

**Comment by mirnovov** [comment] 2023-09-11 03:37
Still can't replicate this. Is this when opening the homepage at startup, or during the course of using your vault? And does it still occur when disabling your other plugins?

**Comment by machado-t** [comment] 2023-09-11 08:53
I believe it only happens at startup. I don't remember it ever happening during the course of using the vault.    
It does not happen always, or it would be easier for me to test. 
Regarding OneDrive, in both laptops the folder is designated as "always available locally".
My best uneducated guess is that this is related to using two laptops, sometimes simultaneously.

**Comment by mirnovov** [comment] 2023-09-12 04:02
Could very well be possible. Unfortunately I don’t have two laptops to test it but I’ll let you know if I manage to reproduce it

**Comment by cabaucom376** [comment] 2023-09-12 16:29
I'm having the exact same issue. I've been dealing with it in the past some but it's become very frequent now. I typically have my laptop plugged in with obsidian running and syncing 24/7. It seems that when I open obsidian it tries to take me to my homepage file and then opens it blank. As my sync log shows it's detecting changes and then uploading the file on startup.

This causes my homepage file to be replaced instantly on my laptop since it's syncing 24/7, and not only that but I have my laptop syncing with a self hosted backup service and it deletes it off my home server too. I've temporarily disabled the plug-in in the meantime.

Here's my list of plug-ins I'm using:

- Advanced Tables
- Better Word Count
- Commander
- Dataview
- Homepage
- Icon Folder
- Map View
- Outliner
- Projects
- QuickAdd
- Tag Wrangler
- Tasks

**Comment by mirnovov** [comment] 2023-09-13 01:35
@machado-t or @cabaucom376 would either of you be able to send me your vaults so I can reproduce this issue? This is quite hard to debug - there's nothing in the code that should affect the file in any way if you have autoCreate turned off, but I've found previously that doing innocuous-looking stuff with the core Obsidian API can have unintended side effects including this. I'm not able to get it to happen myself but I'd really like to get it fixed as user data loss is a serious issue. 

I can be reached at anon185441@gmail.com.

**Comment by machado-t** [comment] 2023-09-13 22:09
autoCreate is indeed turned off on all devices.
I'm afraid I cant share the vault right now, as I would need to delete or anonymize some data before sending. Is the homepage .md file of any help right now?

**Comment by mirnovov** [comment] 2023-09-13 23:43
Totally understand, just the homepage would be great if you can send that.

**Comment by mirnovov** [comment] 2023-09-17 08:45
Thanks for sending the pages - unfortunately I still can't reproduce this. I'll leave the issue open and update it if a cause and/or solution is found.

**Comment by mirnovov** [comment] 2024-01-26 02:55
@Giulidan unfortunately I wasn't able to make any headway solving this issue. I would appreciate a few details from you if you don't mind, it may help me get to the bottom of it.

Do you use a non-Obsidian sync solution? And can you share what OS you've on and the Homepage debug info? (The latter is a button at the bottom of the Homepage settings page).

**Comment by mirnovov** [comment] 2024-01-26 03:35
I have pushed a fix that will appear in the next version but I'd still be interested in this information.

**Closed** 2024-01-26 03:34 UTC
Labels: bug, cantrepro
