### ISSUE TITLE
[BUG] Tabs are not rendered in Obsidian 1.2.2

### ISSUE THREAD

**Issue by OmniNaut** [mirnovov/obsidian-homepage#44] opened 2023-04-07 05:12 UTC
### Summary

Since the update to Obsidian 1.2.X the plugin does not render tabs anymore

### Steps to reproduce

Plugin enabled:
![image](https://user-images.githubusercontent.com/110312864/230545100-e89aa73f-78b1-4546-9356-be0d3d993604.png)

Should be:
![image](https://user-images.githubusercontent.com/110312864/230545270-2b590776-2690-4197-ba35-d776c36c0130.png)

### Obsidian info

![image](https://user-images.githubusercontent.com/110312864/230545018-04097fe7-e04c-4476-bae8-6cccfd4b0631.png)

Happens with default theme and minimal theme

### Obsidian version

1.2.2 Windows

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment] 2023-04-07 06:37
Unfortunately I'm not part of the insider program, so I can't debug this. I'll wait until 1.2.x is released to the public.

**Comment by OmniNaut** [comment] 2023-04-13 03:56
> ~ I've purchased an Catalyst license and have developed a fix that works on 1.2.x.

Awesome, welcome to the catalyst club 👍🏼

**Comment by OmniNaut** [comment] 2023-04-14 22:24
It is still broken for me with version 3.0 of the plugin. Obsidian upgraded also to 1.2.3 automatically, so I don't know if the issue was fixed for 1.2.2 and regressed back into 1.2.3.

**Comment by mirnovov** [comment] 2023-04-14 23:47
Sorry about that. 

Unfortunately, I can't seem to reproduce this on 1.2.3. Have you got any conflicting plugins that might be causing any issues?  3.0 has a new "copy debug info" button at the bottom of my settings pane that lists them all, so you can just copy that.

**Comment by OmniNaut** [comment] 2023-04-15 04:13
> Sorry about that.
> 
> Unfortunately, I can't seem to reproduce this on 1.2.3. Have you got any conflicting plugins that might be causing any issues? 3.0 has a new "copy debug info" button at the bottom of the homepage settings pane that lists them all, so you can just copy that.

On your suggesting I disabled and individually enabled community plugins again. I found the culprit.
It's the plugin [Obsidian New Tab](https://github.com/patleeman/obsidian-open-in-new-tab). It's just a simple plugin without any further options to experiment with.

Unfortunately I can't find the "copy debug info" button you're talking about. Can you point me in the right direction?

**Comment by mirnovov** [comment] 2023-04-15 08:05
> If I disable Homepage and enable New Tab the expected behaviour is fine. It's only the combination of the two plugins that makes this behaviour appear.
I cannot tell which of the two plugins is the real culprit in this.

Thanks for the pointer - I'll sort something out and/or include a fix for it in an upcoming release. I already have special case code for other plugins which interact with tabs.

> Unfortunately I can't find the "copy debug info" button you're talking about. Can you point me in the right direction?

It's at the bottom right of the homepage settings:

<img width="1123" alt="Untitled" src="https://user-images.githubusercontent.com/73574818/232198803-37d6d766-dbef-4823-97e7-ac4d0eb55757.png">

I know it's not the most obvious but given that most users won't use it I didn't want it to get in the way.

**Comment by OmniNaut** [comment] 2023-04-15 09:19
![image](https://user-images.githubusercontent.com/110312864/232204378-d00c1cfe-0b7d-4a65-9fe9-7826957025f0.png)

I have completely different settings page

**Comment by OmniNaut** [comment] 2023-04-15 09:27
Ok, I have reinstalled the plugin and now I have the correct settings page.
I copied the debug info

{"version":3,"homepages":{"Main Homepage":{"value":"Dashboard.canvas","kind":"File","openOnStartup":true,"hasRibbonIcon":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Default view","revertView":true,"refreshDataview":false,"autoCreate":true,"autoScroll":false,"pin":false,"commands":[]}},"separateMobile":false,"_plugins":["obsidian-audio-notes","obsidian-auto-hide","awesome-reader","buttons","obsidian-chartsview-plugin","dataview","creases","dbfolder","double-colon-conceal","obsidian-excalidraw-plugin","obsidian-full-calendar","heading-level-indent","local-quotes","make-md","metadata-menu","periodic-notes","obsidian-minimal-settings","pinterest-widget-obsidian","obsidian-projects","quickadd","obsidian-style-settings","templater-obsidian","obsidian-toggle-meta-yaml-plugin","obsidian-tracker","open-in-new-tab","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","canvas","outgoing-link","tag-pane","page-preview","note-composer","command-palette","editor-status","bookmarks","outline","file-recovery"],"_obsidianVersion":"1.2.3"}

**Comment by mirnovov** [comment] 2023-04-15 09:35
Seems like the settings page broke for some reason, I'll look into that. Anyway, it's definitely `open-in-new-tab` causing your problems, I can reproduce it now.

**Comment by mirnovov** [comment] 2023-04-15 10:20
Unfortunately, I can't really create a fix on my end, so I've submitted [a PR](https://github.com/patleeman/obsidian-open-in-new-tab/pull/9) to the developer of the `open-in-new-tab` plugin. Hopefully they implement it, though ofc it's ultimately up to them. 

BTW, the issue that lead to your settings not working earlier should be fixed in 837dcf5. Thanks for the help finding the root of this problem @OmniNaut, it's very much appreciated.

**Closed by mirnovov** 2023-04-15 10:20 UTC
Labels: bug

**Comment by OmniNaut** [comment] 2023-04-16 01:25
Thanks for your effort as well 👍🏼

**Comment by peterzhu1992** [comment] 2023-06-23 17:21
Since there is no attraction in https://github.com/patleeman/obsidian-open-in-new-tab/pull/9, I just go ahead and include @mirnovov fix in my own fork, and release on BRAT so if anyone has this conflict they can use it.
https://github.com/peterzhu1992/obsidian-open-in-new-tab-homepage-fix/releases/tag/1.0.9h

Thanks.
