### ISSUE TITLE
Open a Workspace breaks Obsidian's sidebars on iOS

### ISSUE THREAD

**Issue by tralce** [mirnovov/obsidian-homepage#70] opened 2023-09-30 16:51 UTC
### Details

(I mean the sidebars that you swipe in from the sides)

When Homepage is enabled and set to load a Workspace, on load, Homepage loads the Workspace as expected, however the sidebars which usually contain such things as the Files view and the Tag view become empty. They only display a Settings gear (iPhone only) and a Vault selector (iPhone and iPad)

If I enable Separate mobile homepage and instruct it to open a regular file, this does not happen.

### Steps to reproduce

1. Save a workspace
2. Tell Homepage on an iOS device to load the Workspace on load
3. Relaunch the app
4. Try to open the sidebars
5. Unhappy empty sidebar times

### Debug information

```shell
I do not see the option to do that on iOS where the issue is actually happening. Here's one from my Linux laptop where it is not happening. 

{"version":3,"homepages":{"Main Homepage":{"value":"Default","kind":"Workspace","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Replace all open notes","view":"Reading view","revertView":true,"openWhenEmpty":true,"refreshDataview":false,"autoCreate":true,"autoScroll":false,"pin":true,"commands":[],"alwaysApply":true},"Mobile Homepage":{"value":"Obsidian","kind":"File","openOnStartup":true,"openMode":"Replace all open notes","manualOpenMode":"Replace all open notes","view":"Reading view","revertView":true,"openWhenEmpty":true,"refreshDataview":false,"autoCreate":true,"autoScroll":false,"pin":true,"commands":[],"alwaysApply":true}},"separateMobile":true,"_defaultViewMode":"source","_livePreview":"default","_focusNewTab":"default","_plugins":["table-editor-obsidian","obsidian-kanban","obsidian-tasks-plugin","obsidian-auto-link-title","obsidian-linter","folder-note-plugin","obsidian-excel-to-markdown-table","notion-like-tables","omnisearch","homepage","url-into-selection","cm-editor-syntax-highlight-obsidian","find-unlinked-files","index-checker"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","properties","daily-notes","note-composer","command-palette","editor-status","outline","word-count","workspaces","file-recovery","sync"],"_obsidianVersion":"1.4.14"}
```

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment] 2023-10-01 07:56
Thanks for the bug report. Does this occur when opening the workspace normally? (without using Homepage, but with the built-in workspace manager)

**Comment by 0ge** [comment] 2023-10-07 19:30
I had the [same issue](https://forum.obsidian.md/t/sidebar-content-gone-on-ios/68401/6).

For me it reproduced when manually opening the workspace. If I disable the plugin it keeps happening.

**Comment by mirnovov** [comment] 2023-10-08 08:49
Yes, this seems like a duplicate of #48, but I can't confirm that yet.

**Comment by mirnovov** [comment] 2023-10-09 04:58
Just tested it, and the issue still occurs when opening a workspace that's created on desktop on mobile, even without using Homepage. Therefore, I'm closing as a duplicate of #48.

**Closed by mirnovov** 2023-10-09 04:58 UTC
Labels: bug
