### ISSUE TITLE
MacOS - on obsidian startup, repeatedly opens TextEdit

### ISSUE THREAD

**Issue by AdrianOrenstein** [mirnovov/obsidian-homepage#50] opened 2023-05-31 02:09 UTC
### Details

When opening Obsidian and reaching the "Loading Workspace" stage, this plugin will open TextEdit's README. This doesn't occur in version 3.0.2, but does in 3.1. 

If the "README.md" file exists, this bug does not occur. If README.md is not present, MacOS will continually open TextEdit until Obsidian is terminated. 

Setting "Main Homepage" to : { "value": "README", ... } causes the problem if a directory named "README/" is present.
Setting "Main Homepage" to : { "value": "README.md", ... } works.

### Steps to reproduce

Edit: Now reproducible with a minimal example

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment] 2023-05-31 03:26
I can't reproduce this, and this is very weird - I can't see anything in the plugin doing this. Have you got any other plugins enabled? And what settings do you have the Homepage plugin set to? (If you click the "Copy debug info" button down the bottom it should copy them all)

**Comment by fpopineau** [comment] 2023-07-10 17:58
I can observe that too under Windows with a very large vault.
If I restart Windows with Obsidian set to launch when I log in, 
then while Obsidian is loading its cache, I get a Windows modal window asking which app to open Home
then I get a black screen.

I tried to debug that and run Obsidian from the command line.
When I get the black screen,
I can see this error message in the console
```
2023-07-10 17:46:13 App is up to date.
[2504:0710/194816.545:ERROR:crashpad_client_win.cc(844)] not connected
```
I suspect that the Homepage plugin is trigering some problem underneath in Electron.
Among the plugins I have installed, if I remove Homepage and Banners, the problem disappears.
Also, when the Homepage plugin is active, I see a long timeout before getting the black screen.
```
{"version":3,"homepages":{"Main Homepage":{"value":"Home","kind":"File","openOnStartup":true,"hasRibbonIcon":true,"openMode":"Replace all open notes","manualOpenMode":"Keep open notes","view":"Reading view","revertView":true,"refreshDataview":true,"autoCreate":false,"autoScroll":false,"pin":false,"commands":[],"openWhenEmpty":true}},"separateMobile":false,"_defaultViewMode":"default","_livePreview":true,"_focusNewTab":"default","_plugins":["obsidian-admonition","table-editor-obsidian","obsidian-advanced-uri","obsidian-file-link","bibnotes","calendar","obsidian-citation-plugin","obsidian-editor-shortcuts","obsidian-contextual-typography","dataview","obsidian-emoji-toolbar","obsidian-excalidraw-plugin","extract-url","obsidian-full-calendar","obsidian-hider","obsidian-linter","obsidian-media-db-plugin","obsidian-minimal-settings","note-refactor-obsidian","obsidian-pandoc","obsidian-pandoc-reference-list","obsidian-paste-image-rename","periodic-notes","obsidian-style-settings","supercharged-links-obsidian","tag-wrangler","obsidian-tasks-plugin","templater-obsidian","update-time-on-edit","obsidian-zotero-desktop-connector","auto-note-mover","obsidian-daily-notes-opener","obsidian-rollover-daily-todos","chatgpt-md","cmdr","obsidian-divide-and-conquer","obsidian-org-mode","homepage"],"_internalPlugins":["file-explorer","global-search","switcher","graph","backlink","canvas","outgoing-link","tag-pane","page-preview","daily-notes","templates","note-composer","command-palette","slash-command","editor-status","bookmarks","markdown-importer","zk-prefixer","outline","word-count","workspaces","file-recovery"],"_obsidianVersion":"1.3.5"}
```

**Comment by AdrianOrenstein** [comment] 2023-07-11 00:47
@fpopineau Can you reproduce with a minimal example?

**Comment by mirnovov** [comment] 2023-07-11 09:41
@AdrianOrenstein does your vault also have a large amount of notes?

**Comment by AdrianOrenstein** [comment] 2023-07-11 12:53
It does

**Comment by mirnovov** [comment] 2023-07-12 03:25
Unfortunately I have tested in a vault with all of fpopineau's plugins and 12000 files and still cannot generate this error :/

However, I've also looked at the differences at 3.2 and 3.0.1 some more, and I think the problem may lie somewhere in the "Revert view" functionality. Does this problem persist if you enable the Homepage plugin but disable that setting?

**Comment by AdrianOrenstein** [comment] 2023-07-12 06:37
I can reproduce the issue on my side by setting the main homepage value to be "README", and making a directory named "README". Reopening Obsidian causes the plugin to open the directory, looping the launching textedit indefinetly. I can exit out of this bootloop by exiting Obisidian. I can workaround this bug by specifying "README.md" and with a "README.md" markdown file present and the plugin then works as expected.

With the bug present, the home page set to "README" with the "README" directory present, disabling the revert view does not fix the issue unfortunately. 

@fpopineau is there a directory named the same as your homepage markdown file? That would help us figure out if there are two different ways to cause the same bug - where textedit tries to open indefinitely.

**Comment by AdrianOrenstein** [comment] 2023-07-12 06:57
I can reproduce with a minimal example now, how can I get that to you? email?

**Comment by mirnovov** [comment] 2023-07-12 08:26
I've managed to reproduce the extensionless file case, but not the directory case. 

The former doesn't appear to be due to Homepage, but due to how base Obsidian handles links (Homepage uses Obsidian's  `openLinkText` to open notes). I can reproduce this when opening an Obsidian link to README with all plugins disabled; it opens the link once in TextEdit. The repeated opening with Homepage seems to be since Obsidian doesn't have a note to return to. The same works with files with any other name, provided it doesn't have an extension.

**Comment by mirnovov** [comment] 2023-07-12 10:34
I have opened a [bug report](https://forum.obsidian.md/t/extensionless-file-with-the-same-name-as-note-opens-instead-of-note-when-making-link/62948) regarding the parts of this issue which appear to be caused by base Obsidian behaviour.

**Comment by fpopineau** [comment] 2023-07-12 13:28
Hi,

Sorry for the delay. Some more information from my side:
- I have two vaults : one small, one large. The problem appears only on the
large vault
- I have a few thousands .md files in the vault, but hundreds of thousands
files
- the problem persists if I turn off the 'Revert view' option
- the Homepage plugin makes it very long to start Obsidian and the memory
footprint of the process seems to grow much larger than without the plugin
(10x) before dropping
- something in Obsidian fails because I get a black screen
- only when Obsidian is started automatically when logging into Windows I
get the notification about what program to use to open Home.md . I can
select notepad and I get a whole HTML page. What happens here is certainly
OS dependent.
And now I am stumped because I renamed the homepage I used from Home.md to
Homepage.md ... and the problem vanished !
Just to make sure, I reversed to Home.md and now I monitor Obsidian.exe for
more than 1h, memory footprint growing, probably rebuilding some cache and
I guess it will crash after that.
Here, Home.md has a homepage does not work and I don't have a Home
directory in the vault, but the vault is located in ***@***.***
I fear that this is no coincidence, and that would mean there is a mess in
the way Obsidian handles filenames.

--
Fabrice

**Comment by mirnovov** [comment] 2023-07-13 02:19
Yeah, that seems like the most plausible explanation. I have made it so the plugin shouldn't get into an infinite loop when it has trouble opening the file, and instead resolve more gracefully. But how it deals with filenames is core Obsidian logic, and it seems unwise to work around that behaviour if can be fixed by the core Obsidian developers.

**Comment by AdrianOrenstein** [comment] 2023-07-14 06:09
In the homepage settings GUI, it doesn't include the suffix ".md", which might inadvertently cause the bug for others. Adding the suffix manually doesn't work either. I have to edit the data.json to add the suffix.
<img width="462" alt="image" src="https://github.com/mirnovov/obsidian-homepage/assets/26395770/6a44795d-abe9-4cda-9cd2-90c7ea0c7371">

**Comment by mirnovov** [comment] 2023-07-14 07:32
@AdrianOrenstein if you manually unfocus the suggestion box by clicking it will retain the extension (as opposed to pressing enter which will always choose the first suggestion). 

The omission of the suffix is intentional, as that is consistent with the suggestion dropdown for base Obsidian links.

**Comment by mirnovov** [comment] 2023-08-17 02:02
Closed for now as the remainder of the behaviour is a core Obsidian issue and there is a fairly easy workaround that handles all cases.

**Closed by mirnovov** 2023-08-17 02:02 UTC
Labels: bug, external bug
