### ISSUE TITLE
Left and right side pane not working properly on Android version of Obsidian when homepage is set to open a workspace

### ISSUE THREAD

**Issue by lilyofthealley** [mirnovov/obsidian-homepage#84] opened 2024-03-20 00:40 UTC
### Details

When I open Obsidian, if the homepage plugin is set to open a workspace specifically the side panels are empty. I do not encounter this issue if I set homepage to open a file, a random note or the graph view.

![photo_6039821893877483670_y](https://github.com/mirnovov/obsidian-homepage/assets/132984387/6ee2d5a2-e169-4134-9183-0b5fc5ae4a0b)
![photo_6039821893877483671_y](https://github.com/mirnovov/obsidian-homepage/assets/132984387/9caf63e0-feca-4dab-b68b-5c8d817bc695)

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment] 2024-03-20 04:34
Seems to be a duplicate of #48 and #70. In other words, it’s an issue with Obsidian not this plugin I’m afraid :(

**Closed by mirnovov** 2024-03-20 04:34 UTC
Labels: bug
