### ISSUE TITLE
Plugin Conflict Homepage and File Color

### ISSUE THREAD

**Issue by Trenobol** [mirnovov/obsidian-homepage#106] opened 2024-10-18 19:14 UTC
### Details

When Homepage updating to 4.0.6, the plugin File Color stops working - coloring notebooks in colors
In 4.0.4 is OK

4.0.6:
![IMG_9536](https://github.com/user-attachments/assets/2d5882bd-bccb-4590-b93f-b016954fa99f)

4.0.4:
![1729269936243](https://github.com/user-attachments/assets/25da7440-b2ac-434b-a5e1-2fa12038b244)
![1729270033456](https://github.com/user-attachments/assets/85cfd137-87a0-4997-af0f-1e96998c4378)

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment] 2024-10-19 03:26
Duplicate of #104, the fix for this will be released in an upcoming version.

**Closed by mirnovov** 2024-10-19 03:26 UTC
Labels: bug
